// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Production.Planner.Data;

#nullable disable

namespace agid.production.planner.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241119012025_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Production.Planner.Models.ProductionScheduleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualProduction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hari")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MingguKe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlannedProduction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tahun")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProductionSchedule", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
